const reason = [
  { name: `Africa`, population: `African` },
  { name: `Australia`, population: `Australian` },
  { name: `Brazil`, population: `Brazilian` },
  { name: `Canada`, population: `Canadian` },
  { name: `China`, population: `Chinese` },
  { name: `England`, population: `English` },
  { name: `France`, population: `French` },
  { name: `Germany`, population: `German` },
  { name: `India`, population: `Indian` },
  { name: `Indonesia`, population: `Indonesian` },
  { name: `Ireland`, population: `Irish` },
  { name: `Italy`, population: `Italian` },
  { name: `Japan`, population: `Japanese` },
  { name: `Mexico`, population: `Mexican` },
  { name: `North Korea`, population: `North Korean` },
  { name: `Norway`, population: `Norwegian` },
  { name: `Russia`, population: `Russian` },
  { name: `Saudi Arabia`, population: `Saudi` },
  { name: `Scottland`, population: `Scottish` },
  { name: `South Korea`, population: `South Korean` },
  { name: `Spain`, population: `Spanish` },
  { name: `Sweden`, population: `Swedish` },
  { name: `Switzerland`, population: `Swiss` },
  { name: `Turkey`, population: `Turkish` },
  { name: `Ukraine`, population: `Ukrainian` },
  { name: `United States`, population: `American` },
]

module.exports = reason
