const who = [
    { type: `group-known`, name: `FEMA` },
    { type: `group-known`, name: `Mossad` },
    { type: `group-known`, name: `The Bilderberg Group` },
    { type: `group-known`, name: `The CIA` },
    { type: `group-known`, name: `The Chinese Communist Party` },
    { type: `group-known`, name: `The Church of Scientology` },
    { type: `group-known`, name: `The Democrat Party` },
    { type: `group-known`, name: `The Department of Homeland Security` },
    { type: `group-known`, name: `The FBI` },
    { type: `group-known`, name: `The Federal Reserve` },
    { type: `group-known`, name: `The Freemasons` },
    { type: `group-known`, name: `The Globalists` },
    { type: `group-known`, name: `The IMF` },
    { type: `group-known`, name: `The Kardashians` },
    { type: `group-known`, name: `The Mafia` },
    { type: `group-known`, name: `The New World Order` },
    { type: `group-known`, name: `The Republican Party` },
    { type: `group-known`, name: `The TSA` },
    { type: `group-known`, name: `The United Nations` },
    { type: `group-known`, name: `The World Bank` },
    { type: `group-known`, name: `The Zionist` },
    { type: `group-unknown`, name: `Alien Human Hybrids` },
    { type: `group-unknown`, name: `Animal Human Hybrids` },
    { type: `group-unknown`, name: `Blue Avians` },
    { type: `group-unknown`, name: `Extraterrestrials` },
    { type: `group-unknown`, name: `Interdimensional Space Elves` },
    { type: `group-unknown`, name: `Lizard People` },
    { type: `group-unknown`, name: `The Black Nobility` },
    { type: `group-unknown`, name: `The Illuminati` },
    { type: `group-unknown`, name: `The Rosicrucians` },
    { type: `man`, name: `Alex Jones` },
    { type: `man`, name: `Barrack Obama` },
    { type: `man`, name: `Bill Clinton` },
    { type: `man`, name: `Bill Gates` },
    { type: `man`, name: `Dick Cheney` },
    { type: `man`, name: `Donald Trump` },
    { type: `man`, name: `Elon Musk` },
    { type: `man`, name: `George H. W. Bush` },
    { type: `man`, name: `George Soros` },
    { type: `man`, name: `George W. Bush` },
    { type: `man`, name: `Jay-Z` },
    { type: `man`, name: `Jeff Bezos` },
    { type: `man`, name: `Joe Biden` },
    { type: `man`, name: `Kanye West` },
    { type: `man`, name: `Martin Shkreli` },
    { type: `man`, name: `Satan` },
    { type: `man`, name: `Vladimir Putin` },
    { type: `woman`, name: `Beyoncé` },
    { type: `woman`, name: `Caitlyn Jenner` },
    { type: `woman`, name: `Chelsea Clinton` },
    { type: `woman`, name: `Hillary Clinton` },
    { type: `woman`, name: `Ivanka Trump` },
    { type: `woman`, name: `Kamala Harris` },
    { type: `woman`, name: `Lady Gaga` },
    { type: `woman`, name: `Madonna` },
    { type: `woman`, name: `Melania Trump` },
    { type: `woman`, name: `Michelle Obama` },
    { type: `woman`, name: `The Queen of England` },
];

module.exports = who;
